"""Delivery Formatter — converts PipelineResult into human-readable output.

Renders the complete delivery package for each tier with appropriate detail.
"""

from __future__ import annotations

from prompt_production.pipeline import PipelineResult
from prompt_production.types import Tier


class DeliveryFormatter:
    """Formats pipeline results for user delivery."""

    def format(self, result: PipelineResult) -> str:
        """Format a complete pipeline result as readable output."""
        sections: list[str] = []

        # Header
        tier = result.task_graph.overall_tier
        approach = result.niche_profile.approach.value.replace("_", " ").title()
        sections.append("# Prompt Production Output\n")
        sections.append(f"**Domain:** {result.niche_profile.domain}")
        sections.append(f"**Tier:** {tier.value} ({tier.name}) | **Approach:** {approach}")
        sections.append(f"**Model:** {result.niche_profile.model_recommendation}")
        sections.append(f"**Gate:** {'PASSED' if result.passed_gate else 'DELIVERED WITH CAVEATS'}")

        # Technique selection
        ts = result.technique_selection
        recipe = f" (recipe: {ts.recipe_name})" if ts.recipe_name else ""
        sections.append(f"\n## Techniques Selected{recipe}\n")
        for t in ts.techniques:
            sections.append(f"- {t}")
        sections.append(f"\n*Reasoning:* {ts.reasoning}")

        # Generated prompt(s)
        sections.append(f"\n## Generated Prompt{'s' if len(result.generated_prompts) > 1 else ''}\n")
        for i, p in enumerate(result.generated_prompts):
            role = p.metadata.get("agent_role", "primary")
            if len(result.generated_prompts) > 1:
                sections.append(f"### Prompt {i + 1}: {role}\n")
            sections.append(f"**Tokens:** {p.token_count} | **Version:** {p.version}\n")
            sections.append(f"```\n{p.content}\n```")

        # Token budget (Tier 3+)
        if tier.value >= Tier.COMPLEX.value:
            budget = result.primary_prompt.metadata.get("token_budget")
            if budget:
                sections.append("\n## Token Budget\n")
                sections.append("| Section | % | Tokens |")
                sections.append("|---------|---|--------|")
                for name, alloc in budget.items():
                    sections.append(f"| {name} | {alloc['percent']:.1f}% | {alloc['tokens']:,} |")

        # Eval suite
        fw = result.eval_framework
        golden = [t for t in fw.test_cases if t.category == "golden"]
        adversarial = [t for t in fw.test_cases if t.category == "adversarial"]
        edge = [t for t in fw.test_cases if t.category == "edge_case"]
        sections.append(f"\n## Eval Suite ({len(fw.test_cases)} tests)\n")
        sections.append(f"**Golden:** {len(golden)} | **Adversarial:** {len(adversarial)} | **Edge:** {len(edge)}")
        sections.append(f"**Pass threshold:** {fw.rubric.pass_threshold}")
        sections.append("\n| ID | Category | Input | Expected |")
        sections.append("|----|----------|-------|----------|")
        for tc in fw.test_cases[:8]:
            inp = tc.input_text[:40] + "..." if len(tc.input_text) > 40 else tc.input_text
            exp = tc.expected_behavior[:40] + "..." if len(tc.expected_behavior) > 40 else tc.expected_behavior
            sections.append(f"| {tc.id} | {tc.category} | {inp} | {exp} |")
        if len(fw.test_cases) > 8:
            sections.append(f"| ... | ... | *{len(fw.test_cases) - 8} more tests* | ... |")

        # Test results
        tb = result.testbench_result
        sections.append("\n## Test Results\n")
        sections.append(f"- **Structural:** {tb.result.structural.score:.1f}/10")
        if tb.result.structural.antipatterns_found:
            sections.append(f"  - Anti-patterns: {', '.join(tb.result.structural.antipatterns_found)}")
        sections.append(
            f"- **Behavioral:** {tb.result.behavioral.tests_passed}/{tb.result.behavioral.tests_total} passed"
        )
        reg = tb.result.regression
        reg_text = "Baseline established" if reg.is_baseline else f"Delta: {reg.score_delta:+.2f}"
        sections.append(f"- **Regression:** {reg_text}")

        # Failure modes
        if result.failure_modes:
            sections.append("\n## Failure Modes\n")
            for fm in result.failure_modes:
                sections.append(f"- {fm}")

        # Compliance
        if result.niche_profile.compliance_requirements:
            sections.append("\n## Compliance\n")
            for c in result.niche_profile.compliance_requirements:
                sections.append(f"- {c}")

        # Version info
        prompt_count = len(result.generated_prompts)
        sections.append(
            f"\n---\n*Generated by Prompt Production v0.1.0 | Tier {tier.value} | {prompt_count} prompt(s)*"
        )

        return "\n".join(sections)
